services:
  db:
    image: postgres:15
    container_name: postgres
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB -p $POSTGRES_PORT"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: "15s"

  backend:
    container_name: backend
    build:
      context: ../
      dockerfile: ./Dockerfile
      target: prod
    env_file:
      - ../.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/v1/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: "10s"

volumes:
  postgres_data:



