"""add user_id to request

Revision ID: 3445f3fd9e18
Revises: 214bd905d41d
Create Date: 2025-05-01 01:00:45.155766

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3445f3fd9e18'
down_revision = '214bd905d41d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('completed_request')
    op.drop_table('telegram_profile')
    op.add_column('request', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'request', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.drop_column('request', 'user_id')
    op.create_table('telegram_profile',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='telegram_profile_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='telegram_profile_pkey')
    )
    op.create_table('completed_request',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('client_phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('insect_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('treatment', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='completed_request_pkey')
    )
    # ### end Alembic commands ###
