"""add verif

Revision ID: 4ed65b2c6f7d
Revises: d4fd70e9645a
Create Date: 2025-04-25 17:15:59.051830

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4ed65b2c6f7d'
down_revision = 'd4fd70e9645a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('verification_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('client', sa.Column('verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'verified')
    op.drop_column('client', 'verification_code')
    # ### end Alembic commands ###
