"""add telegram_profile

Revision ID: 79ef0cfe26e5
Revises: 3445f3fd9e18
Create Date: 2025-05-01 01:27:40.946754

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '79ef0cfe26e5'
down_revision = '3445f3fd9e18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
