"""expand analytics_raw with full payload

Revision ID: 801b5bc5a3ec
Revises: de5d8f98d8a0
Create Date: 2025-05-21 16:52:49.165217

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '801b5bc5a3ec'
down_revision = 'de5d8f98d8a0'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('analyticsraw', sa.Column('treatment', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('analyticsraw', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('analyticsraw', sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('analyticsraw', sa.Column('executor_id', sa.Integer(), nullable=True))
    op.add_column('analyticsraw', sa.Column('executor_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('analyticsraw', sa.Column('executor_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('analyticsraw', sa.Column('recorded_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyticsraw', sa.Column('executor', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('analyticsraw', 'recorded_at')
    op.drop_column('analyticsraw', 'executor_phone')
    op.drop_column('analyticsraw', 'executor_name')
    op.drop_column('analyticsraw', 'executor_id')
    op.drop_column('analyticsraw', 'comment')
    op.drop_column('analyticsraw', 'price')
    op.drop_column('analyticsraw', 'treatment')
    # ### end Alembic commands ###
