"""recreate telegram_profile and completed_request

Revision ID: aeb15afd1d94
Revises: 79ef0cfe26e5
Create Date: 2025-05-01 01:32:31.958813

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aeb15afd1d94'
down_revision = '79ef0cfe26e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
