"""add remindeer archive

Revision ID: ce414d5e1ecc
Revises: 52cdf80a8164
Create Date: 2025-04-29 19:09:32.382547

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ce414d5e1ecc'
down_revision = '52cdf80a8164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminderarchive',
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('remind_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminderarchive')
    # ### end Alembic commands ###
