"""update client

Revision ID: e1ea2fa6c80a
Revises: e603c43aa245
Create Date: 2025-04-25 22:37:08.526819

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e1ea2fa6c80a'
down_revision = 'e603c43aa245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'name')
    op.drop_column('client', 'city')
    op.drop_column('client', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('client', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('client', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
