"""create valid

Revision ID: e603c43aa245
Revises: 4ed65b2c6f7d
Create Date: 2025-04-25 18:54:18.411656

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e603c43aa245'
down_revision = '4ed65b2c6f7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
