"""initial migration

Revision ID: f6298e858321
Revises: a0f1ff20194c
Create Date: 2025-04-23 21:12:30.505386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f6298e858321'
down_revision: Union[str, None] = 'a0f1ff20194c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('client_price', sa.Float(), nullable=False))
    op.add_column('request', sa.Column('final_price', sa.Float(), nullable=True))
    op.add_column('request', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('request', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('request', 'description')
    op.drop_column('request', 'final_price')
    op.drop_column('request', 'client_price')
    # ### end Alembic commands ###
